language: python
sudo: false
python:
 - "3.4"
 - "3.5"

install:
 - pip install -e .
 - pip install -r etc/requirements_dev.txt

before_script:
 - flake8 lazy/

script:
 - py.test

notifications:
  email: false
